// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalling.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ICECredentialType int32

const (
	ICECredentialType_PASSWORD ICECredentialType = 0
	ICECredentialType_OAUTH    ICECredentialType = 1
)

var ICECredentialType_name = map[int32]string{
	0: "PASSWORD",
	1: "OAUTH",
}

var ICECredentialType_value = map[string]int32{
	"PASSWORD": 0,
	"OAUTH":    1,
}

func (x ICECredentialType) String() string {
	return proto.EnumName(ICECredentialType_name, int32(x))
}

func (ICECredentialType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{0}
}

type NewUserParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserParam) Reset()         { *m = NewUserParam{} }
func (m *NewUserParam) String() string { return proto.CompactTextString(m) }
func (*NewUserParam) ProtoMessage()    {}
func (*NewUserParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{0}
}

func (m *NewUserParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserParam.Unmarshal(m, b)
}
func (m *NewUserParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserParam.Marshal(b, m, deterministic)
}
func (m *NewUserParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserParam.Merge(m, src)
}
func (m *NewUserParam) XXX_Size() int {
	return xxx_messageInfo_NewUserParam.Size(m)
}
func (m *NewUserParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserParam.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserParam proto.InternalMessageInfo

func (m *NewUserParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewUserParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserParam) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type GetUserParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserParam) Reset()         { *m = GetUserParam{} }
func (m *GetUserParam) String() string { return proto.CompactTextString(m) }
func (*GetUserParam) ProtoMessage()    {}
func (*GetUserParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{1}
}

func (m *GetUserParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserParam.Unmarshal(m, b)
}
func (m *GetUserParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserParam.Marshal(b, m, deterministic)
}
func (m *GetUserParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserParam.Merge(m, src)
}
func (m *GetUserParam) XXX_Size() int {
	return xxx_messageInfo_GetUserParam.Size(m)
}
func (m *GetUserParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserParam proto.InternalMessageInfo

func (m *GetUserParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{3}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserProfileParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileParam) Reset()         { *m = UpdateUserProfileParam{} }
func (m *UpdateUserProfileParam) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileParam) ProtoMessage()    {}
func (*UpdateUserProfileParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{4}
}

func (m *UpdateUserProfileParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileParam.Unmarshal(m, b)
}
func (m *UpdateUserProfileParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileParam.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileParam.Merge(m, src)
}
func (m *UpdateUserProfileParam) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileParam.Size(m)
}
func (m *UpdateUserProfileParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileParam.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileParam proto.InternalMessageInfo

func (m *UpdateUserProfileParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserProfileParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserProfileParam) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type UpdateProfileParam struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileParam) Reset()         { *m = UpdateProfileParam{} }
func (m *UpdateProfileParam) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileParam) ProtoMessage()    {}
func (*UpdateProfileParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{5}
}

func (m *UpdateProfileParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileParam.Unmarshal(m, b)
}
func (m *UpdateProfileParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileParam.Marshal(b, m, deterministic)
}
func (m *UpdateProfileParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileParam.Merge(m, src)
}
func (m *UpdateProfileParam) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileParam.Size(m)
}
func (m *UpdateProfileParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileParam.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileParam proto.InternalMessageInfo

func (m *UpdateProfileParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProfileParam) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *UpdateProfileParam) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Profile struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string       `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Servers              []*ICEServer `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{6}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Profile) GetServers() []*ICEServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

type ICEServer struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CredentialType       ICECredentialType `protobuf:"varint,3,opt,name=credentialType,proto3,enum=protos.ICECredentialType" json:"credentialType,omitempty"`
	Password             string            `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AccessToken          string            `protobuf:"bytes,5,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	MacKey               string            `protobuf:"bytes,6,opt,name=macKey,proto3" json:"macKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ICEServer) Reset()         { *m = ICEServer{} }
func (m *ICEServer) String() string { return proto.CompactTextString(m) }
func (*ICEServer) ProtoMessage()    {}
func (*ICEServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{7}
}

func (m *ICEServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ICEServer.Unmarshal(m, b)
}
func (m *ICEServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ICEServer.Marshal(b, m, deterministic)
}
func (m *ICEServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICEServer.Merge(m, src)
}
func (m *ICEServer) XXX_Size() int {
	return xxx_messageInfo_ICEServer.Size(m)
}
func (m *ICEServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ICEServer.DiscardUnknown(m)
}

var xxx_messageInfo_ICEServer proto.InternalMessageInfo

func (m *ICEServer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ICEServer) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ICEServer) GetCredentialType() ICECredentialType {
	if m != nil {
		return m.CredentialType
	}
	return ICECredentialType_PASSWORD
}

func (m *ICEServer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ICEServer) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ICEServer) GetMacKey() string {
	if m != nil {
		return m.MacKey
	}
	return ""
}

type UserAccessToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAccessToken) Reset()         { *m = UserAccessToken{} }
func (m *UserAccessToken) String() string { return proto.CompactTextString(m) }
func (*UserAccessToken) ProtoMessage()    {}
func (*UserAccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{8}
}

func (m *UserAccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccessToken.Unmarshal(m, b)
}
func (m *UserAccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccessToken.Marshal(b, m, deterministic)
}
func (m *UserAccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccessToken.Merge(m, src)
}
func (m *UserAccessToken) XXX_Size() int {
	return xxx_messageInfo_UserAccessToken.Size(m)
}
func (m *UserAccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccessToken proto.InternalMessageInfo

func (m *UserAccessToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type NewRoomParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UserIDs              []string `protobuf:"bytes,5,rep,name=userIDs,proto3" json:"userIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRoomParam) Reset()         { *m = NewRoomParam{} }
func (m *NewRoomParam) String() string { return proto.CompactTextString(m) }
func (*NewRoomParam) ProtoMessage()    {}
func (*NewRoomParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{9}
}

func (m *NewRoomParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoomParam.Unmarshal(m, b)
}
func (m *NewRoomParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoomParam.Marshal(b, m, deterministic)
}
func (m *NewRoomParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoomParam.Merge(m, src)
}
func (m *NewRoomParam) XXX_Size() int {
	return xxx_messageInfo_NewRoomParam.Size(m)
}
func (m *NewRoomParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoomParam.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoomParam proto.InternalMessageInfo

func (m *NewRoomParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewRoomParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewRoomParam) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *NewRoomParam) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewRoomParam) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Users                []*User  `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{10}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Room) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Room) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateRoomProfileParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoomProfileParam) Reset()         { *m = UpdateRoomProfileParam{} }
func (m *UpdateRoomProfileParam) String() string { return proto.CompactTextString(m) }
func (*UpdateRoomProfileParam) ProtoMessage()    {}
func (*UpdateRoomProfileParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{11}
}

func (m *UpdateRoomProfileParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoomProfileParam.Unmarshal(m, b)
}
func (m *UpdateRoomProfileParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoomProfileParam.Marshal(b, m, deterministic)
}
func (m *UpdateRoomProfileParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoomProfileParam.Merge(m, src)
}
func (m *UpdateRoomProfileParam) XXX_Size() int {
	return xxx_messageInfo_UpdateRoomProfileParam.Size(m)
}
func (m *UpdateRoomProfileParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoomProfileParam.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoomProfileParam proto.InternalMessageInfo

func (m *UpdateRoomProfileParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRoomProfileParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRoomProfileParam) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *UpdateRoomProfileParam) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Rooms struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rooms) Reset()         { *m = Rooms{} }
func (m *Rooms) String() string { return proto.CompactTextString(m) }
func (*Rooms) ProtoMessage()    {}
func (*Rooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{12}
}

func (m *Rooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rooms.Unmarshal(m, b)
}
func (m *Rooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rooms.Marshal(b, m, deterministic)
}
func (m *Rooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rooms.Merge(m, src)
}
func (m *Rooms) XXX_Size() int {
	return xxx_messageInfo_Rooms.Size(m)
}
func (m *Rooms) XXX_DiscardUnknown() {
	xxx_messageInfo_Rooms.DiscardUnknown(m)
}

var xxx_messageInfo_Rooms proto.InternalMessageInfo

func (m *Rooms) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type UserRoomParam struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomID               string   `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoomParam) Reset()         { *m = UserRoomParam{} }
func (m *UserRoomParam) String() string { return proto.CompactTextString(m) }
func (*UserRoomParam) ProtoMessage()    {}
func (*UserRoomParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{13}
}

func (m *UserRoomParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoomParam.Unmarshal(m, b)
}
func (m *UserRoomParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoomParam.Marshal(b, m, deterministic)
}
func (m *UserRoomParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoomParam.Merge(m, src)
}
func (m *UserRoomParam) XXX_Size() int {
	return xxx_messageInfo_UserRoomParam.Size(m)
}
func (m *UserRoomParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoomParam.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoomParam proto.InternalMessageInfo

func (m *UserRoomParam) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserRoomParam) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

type GetRoomParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomParam) Reset()         { *m = GetRoomParam{} }
func (m *GetRoomParam) String() string { return proto.CompactTextString(m) }
func (*GetRoomParam) ProtoMessage()    {}
func (*GetRoomParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{14}
}

func (m *GetRoomParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomParam.Unmarshal(m, b)
}
func (m *GetRoomParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomParam.Marshal(b, m, deterministic)
}
func (m *GetRoomParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomParam.Merge(m, src)
}
func (m *GetRoomParam) XXX_Size() int {
	return xxx_messageInfo_GetRoomParam.Size(m)
}
func (m *GetRoomParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomParam proto.InternalMessageInfo

func (m *GetRoomParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PaginationParam struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationParam) Reset()         { *m = PaginationParam{} }
func (m *PaginationParam) String() string { return proto.CompactTextString(m) }
func (*PaginationParam) ProtoMessage()    {}
func (*PaginationParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{15}
}

func (m *PaginationParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationParam.Unmarshal(m, b)
}
func (m *PaginationParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationParam.Marshal(b, m, deterministic)
}
func (m *PaginationParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationParam.Merge(m, src)
}
func (m *PaginationParam) XXX_Size() int {
	return xxx_messageInfo_PaginationParam.Size(m)
}
func (m *PaginationParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationParam.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationParam proto.InternalMessageInfo

func (m *PaginationParam) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PaginationParam) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PaginationParam) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SDP struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}
func (*SDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{16}
}

func (m *SDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDP.Unmarshal(m, b)
}
func (m *SDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDP.Marshal(b, m, deterministic)
}
func (m *SDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDP.Merge(m, src)
}
func (m *SDP) XXX_Size() int {
	return xxx_messageInfo_SDP.Size(m)
}
func (m *SDP) XXX_DiscardUnknown() {
	xxx_messageInfo_SDP.DiscardUnknown(m)
}

var xxx_messageInfo_SDP proto.InternalMessageInfo

func (m *SDP) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SDP) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SDPParam struct {
	Sdp                  *SDP     `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDPParam) Reset()         { *m = SDPParam{} }
func (m *SDPParam) String() string { return proto.CompactTextString(m) }
func (*SDPParam) ProtoMessage()    {}
func (*SDPParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{17}
}

func (m *SDPParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDPParam.Unmarshal(m, b)
}
func (m *SDPParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDPParam.Marshal(b, m, deterministic)
}
func (m *SDPParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDPParam.Merge(m, src)
}
func (m *SDPParam) XXX_Size() int {
	return xxx_messageInfo_SDPParam.Size(m)
}
func (m *SDPParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SDPParam.DiscardUnknown(m)
}

var xxx_messageInfo_SDPParam proto.InternalMessageInfo

func (m *SDPParam) GetSdp() *SDP {
	if m != nil {
		return m.Sdp
	}
	return nil
}

func (m *SDPParam) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserJoinLeaveRoomEvent struct {
	UserID               string               `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomID               string               `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserJoinLeaveRoomEvent) Reset()         { *m = UserJoinLeaveRoomEvent{} }
func (m *UserJoinLeaveRoomEvent) String() string { return proto.CompactTextString(m) }
func (*UserJoinLeaveRoomEvent) ProtoMessage()    {}
func (*UserJoinLeaveRoomEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f66308029891ad, []int{18}
}

func (m *UserJoinLeaveRoomEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserJoinLeaveRoomEvent.Unmarshal(m, b)
}
func (m *UserJoinLeaveRoomEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserJoinLeaveRoomEvent.Marshal(b, m, deterministic)
}
func (m *UserJoinLeaveRoomEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserJoinLeaveRoomEvent.Merge(m, src)
}
func (m *UserJoinLeaveRoomEvent) XXX_Size() int {
	return xxx_messageInfo_UserJoinLeaveRoomEvent.Size(m)
}
func (m *UserJoinLeaveRoomEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserJoinLeaveRoomEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserJoinLeaveRoomEvent proto.InternalMessageInfo

func (m *UserJoinLeaveRoomEvent) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserJoinLeaveRoomEvent) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *UserJoinLeaveRoomEvent) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ICECredentialType", ICECredentialType_name, ICECredentialType_value)
	proto.RegisterType((*NewUserParam)(nil), "protos.NewUserParam")
	proto.RegisterType((*GetUserParam)(nil), "protos.GetUserParam")
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*Users)(nil), "protos.Users")
	proto.RegisterType((*UpdateUserProfileParam)(nil), "protos.UpdateUserProfileParam")
	proto.RegisterType((*UpdateProfileParam)(nil), "protos.UpdateProfileParam")
	proto.RegisterType((*Profile)(nil), "protos.Profile")
	proto.RegisterType((*ICEServer)(nil), "protos.ICEServer")
	proto.RegisterType((*UserAccessToken)(nil), "protos.UserAccessToken")
	proto.RegisterType((*NewRoomParam)(nil), "protos.NewRoomParam")
	proto.RegisterType((*Room)(nil), "protos.Room")
	proto.RegisterType((*UpdateRoomProfileParam)(nil), "protos.UpdateRoomProfileParam")
	proto.RegisterType((*Rooms)(nil), "protos.Rooms")
	proto.RegisterType((*UserRoomParam)(nil), "protos.UserRoomParam")
	proto.RegisterType((*GetRoomParam)(nil), "protos.GetRoomParam")
	proto.RegisterType((*PaginationParam)(nil), "protos.PaginationParam")
	proto.RegisterType((*SDP)(nil), "protos.SDP")
	proto.RegisterType((*SDPParam)(nil), "protos.SDPParam")
	proto.RegisterType((*UserJoinLeaveRoomEvent)(nil), "protos.UserJoinLeaveRoomEvent")
}

func init() { proto.RegisterFile("signalling.proto", fileDescriptor_39f66308029891ad) }

var fileDescriptor_39f66308029891ad = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xce, 0xcd, 0xbd, 0x9c, 0xa4, 0x6d, 0x32, 0xea, 0xa6, 0x26, 0x88, 0x6e, 0x35, 0x2f, 0x54,
	0x14, 0xa5, 0xab, 0x74, 0xb5, 0x08, 0x81, 0x80, 0xa8, 0xc9, 0xee, 0x96, 0x65, 0x69, 0x64, 0xa7,
	0x42, 0x3c, 0x20, 0xe1, 0xc6, 0x93, 0x60, 0x35, 0xf6, 0x58, 0x9e, 0x69, 0x4b, 0xde, 0x11, 0xff,
	0x83, 0xbf, 0xc4, 0xef, 0xe1, 0x01, 0xcd, 0x8c, 0xed, 0x1d, 0xdb, 0x35, 0xdd, 0x52, 0x78, 0xf2,
	0x9c, 0x39, 0xf7, 0x6f, 0xce, 0xc5, 0xd0, 0x66, 0xde, 0x22, 0x70, 0x96, 0x4b, 0x2f, 0x58, 0xf4,
	0xc3, 0x88, 0x72, 0x8a, 0xd6, 0xe4, 0x87, 0xf5, 0x3e, 0x5c, 0x50, 0xba, 0x58, 0x92, 0x63, 0x49,
	0x5e, 0x5e, 0xcf, 0x8f, 0x89, 0x1f, 0xf2, 0x95, 0x12, 0xea, 0x3d, 0xcd, 0x33, 0xb9, 0xe7, 0x13,
	0xc6, 0x1d, 0x3f, 0x54, 0x02, 0xf8, 0x35, 0xb4, 0xbe, 0x27, 0xb7, 0x17, 0x8c, 0x44, 0x13, 0x27,
	0x72, 0x7c, 0xb4, 0x0d, 0x35, 0xcf, 0x35, 0xab, 0x07, 0xd5, 0xc3, 0x4d, 0xab, 0xe6, 0xb9, 0x08,
	0x41, 0x23, 0x70, 0x7c, 0x62, 0xd6, 0xe4, 0x8d, 0x3c, 0xa3, 0x5d, 0x30, 0xc2, 0x5f, 0x28, 0xa7,
	0x66, 0x5d, 0x5e, 0x2a, 0x02, 0xef, 0x43, 0xeb, 0x15, 0xe1, 0xa5, 0x96, 0xf0, 0x37, 0xd0, 0x10,
	0xcc, 0x47, 0x78, 0x38, 0x02, 0x43, 0x58, 0x60, 0x08, 0x83, 0x71, 0x2d, 0x0e, 0x66, 0xf5, 0xa0,
	0x7e, 0xd8, 0x1c, 0xb4, 0x54, 0x2e, 0xac, 0x2f, 0xb8, 0x96, 0x62, 0x61, 0x0b, 0xba, 0x17, 0xa1,
	0xeb, 0x70, 0x22, 0x23, 0x8a, 0xe8, 0xdc, 0x5b, 0x92, 0xc7, 0xa6, 0xf8, 0x33, 0x20, 0x65, 0x33,
	0x63, 0xef, 0xbd, 0xf5, 0xd1, 0x01, 0x34, 0x5d, 0xc2, 0x66, 0x91, 0x17, 0x72, 0x8f, 0x06, 0x66,
	0x43, 0xf2, 0xf4, 0x2b, 0x1c, 0xc2, 0x7a, 0x6c, 0xfb, 0xdf, 0x87, 0x89, 0x8e, 0x60, 0x9d, 0x91,
	0xe8, 0x46, 0x00, 0xd4, 0x90, 0x00, 0x75, 0x12, 0x80, 0xce, 0x4e, 0xc7, 0xb6, 0xe4, 0x58, 0x89,
	0x04, 0xfe, 0xb3, 0x0a, 0x9b, 0xe9, 0x35, 0x6a, 0x43, 0xfd, 0x3a, 0x5a, 0xc6, 0x5e, 0xc5, 0x11,
	0xf5, 0x60, 0x43, 0x00, 0xaa, 0xb9, 0x4e, 0x69, 0x34, 0x84, 0xed, 0x59, 0x44, 0x5c, 0x12, 0x70,
	0xcf, 0x59, 0x4e, 0x57, 0x21, 0x91, 0x71, 0x6c, 0x0f, 0x3e, 0xd0, 0xfc, 0x9d, 0x66, 0x04, 0xac,
	0x9c, 0x82, 0x30, 0x1f, 0x3a, 0x8c, 0xdd, 0xd2, 0xc8, 0x8d, 0xf1, 0x48, 0x69, 0x01, 0x97, 0x33,
	0x9b, 0x11, 0xc6, 0xa6, 0xf4, 0x8a, 0x04, 0xa6, 0xa1, 0xe0, 0xd2, 0xae, 0x50, 0x17, 0xd6, 0x7c,
	0x67, 0xf6, 0x86, 0xac, 0xcc, 0x35, 0xc9, 0x8c, 0x29, 0xfc, 0x31, 0xec, 0x88, 0x67, 0x1f, 0x6a,
	0xa2, 0xbb, 0x60, 0x70, 0x69, 0x46, 0xe5, 0xa6, 0x08, 0xfc, 0x5b, 0x55, 0xd6, 0xbf, 0x45, 0xa9,
	0xff, 0xc8, 0xe2, 0xb8, 0xff, 0x71, 0x91, 0x09, 0xeb, 0x02, 0xba, 0xb3, 0x11, 0x33, 0x8d, 0x83,
	0xfa, 0xe1, 0xa6, 0x95, 0x90, 0xf8, 0xf7, 0x2a, 0x34, 0x44, 0x0c, 0xff, 0xab, 0xfb, 0xb4, 0x6b,
	0x8c, 0xf2, 0xae, 0xe1, 0x49, 0xd7, 0x48, 0x44, 0xfe, 0x93, 0xae, 0x79, 0x8f, 0xaa, 0x3f, 0x02,
	0x43, 0xf8, 0x93, 0x8d, 0x1d, 0x89, 0x43, 0xbe, 0xb1, 0x05, 0xd7, 0x52, 0x2c, 0xfc, 0x35, 0x6c,
	0xc9, 0x88, 0xd3, 0x27, 0xeb, 0xc2, 0x9a, 0xc2, 0x31, 0x8e, 0x2e, 0xa6, 0xc4, 0xbd, 0xd0, 0x38,
	0x1b, 0xc5, 0x31, 0xc6, 0x54, 0x3c, 0xa8, 0x4a, 0x9f, 0x1c, 0xff, 0x08, 0x3b, 0x13, 0x67, 0xe1,
	0x05, 0x8e, 0x88, 0x2d, 0x75, 0x41, 0xe7, 0x73, 0x46, 0xb8, 0x14, 0x33, 0xac, 0x98, 0x12, 0x09,
	0x2f, 0x3d, 0xdf, 0xe3, 0xd2, 0x83, 0x61, 0x29, 0x42, 0xbc, 0xf3, 0x15, 0x59, 0xc9, 0x92, 0x56,
	0x40, 0x24, 0x24, 0xfe, 0x02, 0xea, 0xf6, 0x68, 0x22, 0xb0, 0xe3, 0xa2, 0x5b, 0x94, 0x4f, 0x79,
	0xce, 0xa3, 0x54, 0x2b, 0xa2, 0x34, 0x84, 0x0d, 0x7b, 0x34, 0x51, 0x01, 0x7d, 0x04, 0x75, 0xe6,
	0x86, 0xd2, 0x40, 0x73, 0xd0, 0x4c, 0x60, 0xb2, 0x47, 0x13, 0x4b, 0xdc, 0x6b, 0x90, 0xd4, 0x74,
	0x48, 0xf0, 0xaf, 0xd0, 0x15, 0xd8, 0x7d, 0x4b, 0xbd, 0xe0, 0x3b, 0xe2, 0xdc, 0xc8, 0x57, 0x1e,
	0xdf, 0x90, 0x80, 0x3f, 0x14, 0x44, 0xd4, 0x87, 0x86, 0x58, 0x25, 0x32, 0xc1, 0xe6, 0xa0, 0xd7,
	0x57, 0x7b, 0xa6, 0x9f, 0xec, 0x99, 0xfe, 0x34, 0xd9, 0x33, 0x96, 0x94, 0xfb, 0xe4, 0x53, 0xe8,
	0x14, 0x86, 0x01, 0x6a, 0xc1, 0xc6, 0x64, 0x68, 0xdb, 0x3f, 0x9c, 0x5b, 0xa3, 0x76, 0x05, 0x6d,
	0x82, 0x71, 0x3e, 0xbc, 0x98, 0xbe, 0x6e, 0x57, 0x07, 0x7f, 0x19, 0xf0, 0x44, 0xc4, 0xf6, 0xd6,
	0x09, 0x9c, 0x05, 0xf1, 0x49, 0xc0, 0xc5, 0x7c, 0xf2, 0x66, 0x04, 0x3d, 0x87, 0x96, 0x45, 0x16,
	0x1e, 0xe3, 0x24, 0x92, 0xdb, 0x64, 0x37, 0xc9, 0x5d, 0xdf, 0x62, 0xbd, 0x4c, 0x6d, 0xe3, 0x0a,
	0x3a, 0x86, 0xf5, 0x78, 0x37, 0xbd, 0x53, 0xd0, 0x97, 0x55, 0x41, 0xe1, 0x39, 0x6c, 0xc4, 0x7c,
	0x86, 0xf6, 0x12, 0x5e, 0xae, 0x2a, 0x7a, 0x5b, 0xba, 0x12, 0xc3, 0x15, 0x34, 0x06, 0x14, 0x6b,
	0x65, 0x26, 0xcf, 0x9d, 0x1e, 0xf7, 0x74, 0x65, 0x4d, 0x1c, 0x57, 0xd0, 0x29, 0x74, 0x0a, 0xab,
	0x0b, 0xed, 0xa7, 0xf2, 0x77, 0x6e, 0xb5, 0x42, 0x06, 0x03, 0x00, 0x8b, 0xf8, 0xf4, 0x86, 0x3c,
	0x20, 0xeb, 0x01, 0xc0, 0x69, 0x44, 0xe2, 0xee, 0xcf, 0x40, 0x9b, 0x76, 0x4b, 0x2f, 0xd3, 0x93,
	0xb8, 0x82, 0x9e, 0x49, 0x68, 0xb3, 0x0a, 0x7a, 0x7b, 0xbd, 0x43, 0x49, 0xb6, 0x38, 0xae, 0xa0,
	0x13, 0x89, 0xad, 0x6a, 0xf8, 0x52, 0x6c, 0xf3, 0x6e, 0x52, 0x4c, 0xb4, 0xc1, 0x94, 0xc7, 0x24,
	0x3f, 0xb3, 0x0a, 0x46, 0x5e, 0xc0, 0xd6, 0xd0, 0x75, 0x45, 0xb2, 0x53, 0x2a, 0x23, 0x7e, 0x92,
	0x99, 0x81, 0xa5, 0x39, 0x7e, 0x0e, 0xed, 0x37, 0xde, 0xec, 0x4a, 0x08, 0xbd, 0x8c, 0xa8, 0xff,
	0x10, 0xd5, 0x13, 0x68, 0x8e, 0x08, 0xe3, 0x11, 0x5d, 0xfd, 0x03, 0x44, 0x39, 0xa5, 0xc1, 0x1f,
	0x0d, 0xe8, 0xd8, 0xe9, 0xff, 0x5e, 0x52, 0xfa, 0x9f, 0x01, 0xbc, 0x22, 0x3c, 0xc9, 0xbd, 0x5b,
	0x68, 0xb9, 0xb1, 0xf8, 0xef, 0xeb, 0xed, 0xa4, 0x88, 0x2a, 0x41, 0x5c, 0x41, 0x5f, 0xc1, 0x56,
	0xe6, 0xb7, 0x05, 0xf5, 0xb2, 0xb8, 0x65, 0x30, 0xbb, 0x43, 0xff, 0x85, 0x74, 0xfc, 0x76, 0x75,
	0xcf, 0x93, 0x15, 0x1e, 0xfa, 0xf8, 0xbe, 0xd2, 0xc8, 0x83, 0x35, 0x86, 0xbd, 0xf3, 0xf9, 0x9c,
	0x44, 0x36, 0x61, 0xcc, 0xa3, 0xc1, 0x48, 0x5b, 0x5e, 0x6d, 0x6d, 0xc6, 0x29, 0xe5, 0x12, 0x00,
	0x70, 0x05, 0xbd, 0x04, 0x73, 0x18, 0xb0, 0xdb, 0x47, 0xdb, 0xf9, 0x12, 0x3a, 0xf6, 0xf5, 0xa5,
	0xd0, 0xbd, 0x24, 0xf6, 0x68, 0x12, 0x0f, 0xca, 0x12, 0xdc, 0xf5, 0x21, 0x8c, 0x2b, 0xcf, 0xaa,
	0xe8, 0x27, 0x78, 0x9a, 0x6a, 0x97, 0x0d, 0xdd, 0x12, 0x5b, 0xfb, 0x7a, 0x6d, 0x15, 0xf5, 0x84,
	0xf9, 0x4b, 0xf5, 0xfb, 0x7f, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x4d, 0x93, 0x9e,
	0x19, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomManagementServiceClient is the client API for RoomManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomManagementServiceClient interface {
	RegisterUser(ctx context.Context, in *NewUserParam, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*User, error)
	GetUsers(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Users, error)
	GetUserAccessToken(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*UserAccessToken, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileParam, opts ...grpc.CallOption) (*User, error)
	RemoveUser(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*User, error)
	CreateRoom(ctx context.Context, in *NewRoomParam, opts ...grpc.CallOption) (*Room, error)
	GetRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Rooms, error)
	GetRooms(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Room, error)
	UpdateRoomProfile(ctx context.Context, in *UpdateRoomProfileParam, opts ...grpc.CallOption) (*Room, error)
	AddUserToRoom(ctx context.Context, in *UserRoomParam, opts ...grpc.CallOption) (*Room, error)
	KickUserFromRoom(ctx context.Context, in *UserRoomParam, opts ...grpc.CallOption) (*Room, error)
	DestroyRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Room, error)
}

type roomManagementServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomManagementServiceClient(cc *grpc.ClientConn) RoomManagementServiceClient {
	return &roomManagementServiceClient{cc}
}

func (c *roomManagementServiceClient) RegisterUser(ctx context.Context, in *NewUserParam, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) GetUser(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) GetUsers(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) GetUserAccessToken(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*UserAccessToken, error) {
	out := new(UserAccessToken)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/GetUserAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileParam, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) RemoveUser(ctx context.Context, in *GetUserParam, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) CreateRoom(ctx context.Context, in *NewRoomParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) GetRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) GetRooms(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/GetRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) UpdateRoomProfile(ctx context.Context, in *UpdateRoomProfileParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/UpdateRoomProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) AddUserToRoom(ctx context.Context, in *UserRoomParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/AddUserToRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) KickUserFromRoom(ctx context.Context, in *UserRoomParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/KickUserFromRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagementServiceClient) DestroyRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.RoomManagementService/DestroyRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomManagementServiceServer is the server API for RoomManagementService service.
type RoomManagementServiceServer interface {
	RegisterUser(context.Context, *NewUserParam) (*User, error)
	GetUser(context.Context, *GetUserParam) (*User, error)
	GetUsers(context.Context, *PaginationParam) (*Users, error)
	GetUserAccessToken(context.Context, *GetUserParam) (*UserAccessToken, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileParam) (*User, error)
	RemoveUser(context.Context, *GetUserParam) (*User, error)
	CreateRoom(context.Context, *NewRoomParam) (*Room, error)
	GetRoom(context.Context, *GetRoomParam) (*Rooms, error)
	GetRooms(context.Context, *PaginationParam) (*Room, error)
	UpdateRoomProfile(context.Context, *UpdateRoomProfileParam) (*Room, error)
	AddUserToRoom(context.Context, *UserRoomParam) (*Room, error)
	KickUserFromRoom(context.Context, *UserRoomParam) (*Room, error)
	DestroyRoom(context.Context, *GetRoomParam) (*Room, error)
}

// UnimplementedRoomManagementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomManagementServiceServer struct {
}

func (*UnimplementedRoomManagementServiceServer) RegisterUser(ctx context.Context, req *NewUserParam) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedRoomManagementServiceServer) GetUser(ctx context.Context, req *GetUserParam) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedRoomManagementServiceServer) GetUsers(ctx context.Context, req *PaginationParam) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedRoomManagementServiceServer) GetUserAccessToken(ctx context.Context, req *GetUserParam) (*UserAccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccessToken not implemented")
}
func (*UnimplementedRoomManagementServiceServer) UpdateUserProfile(ctx context.Context, req *UpdateUserProfileParam) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (*UnimplementedRoomManagementServiceServer) RemoveUser(ctx context.Context, req *GetUserParam) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUser not implemented")
}
func (*UnimplementedRoomManagementServiceServer) CreateRoom(ctx context.Context, req *NewRoomParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedRoomManagementServiceServer) GetRoom(ctx context.Context, req *GetRoomParam) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (*UnimplementedRoomManagementServiceServer) GetRooms(ctx context.Context, req *PaginationParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (*UnimplementedRoomManagementServiceServer) UpdateRoomProfile(ctx context.Context, req *UpdateRoomProfileParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoomProfile not implemented")
}
func (*UnimplementedRoomManagementServiceServer) AddUserToRoom(ctx context.Context, req *UserRoomParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserToRoom not implemented")
}
func (*UnimplementedRoomManagementServiceServer) KickUserFromRoom(ctx context.Context, req *UserRoomParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickUserFromRoom not implemented")
}
func (*UnimplementedRoomManagementServiceServer) DestroyRoom(ctx context.Context, req *GetRoomParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyRoom not implemented")
}

func RegisterRoomManagementServiceServer(s *grpc.Server, srv RoomManagementServiceServer) {
	s.RegisterService(&_RoomManagementService_serviceDesc, srv)
}

func _RoomManagementService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).RegisterUser(ctx, req.(*NewUserParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).GetUser(ctx, req.(*GetUserParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).GetUsers(ctx, req.(*PaginationParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_GetUserAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).GetUserAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/GetUserAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).GetUserAccessToken(ctx, req.(*GetUserParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).RemoveUser(ctx, req.(*GetUserParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).CreateRoom(ctx, req.(*NewRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).GetRoom(ctx, req.(*GetRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/GetRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).GetRooms(ctx, req.(*PaginationParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_UpdateRoomProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomProfileParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).UpdateRoomProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/UpdateRoomProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).UpdateRoomProfile(ctx, req.(*UpdateRoomProfileParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_AddUserToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).AddUserToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/AddUserToRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).AddUserToRoom(ctx, req.(*UserRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_KickUserFromRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).KickUserFromRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/KickUserFromRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).KickUserFromRoom(ctx, req.(*UserRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagementService_DestroyRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagementServiceServer).DestroyRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RoomManagementService/DestroyRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagementServiceServer).DestroyRoom(ctx, req.(*GetRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.RoomManagementService",
	HandlerType: (*RoomManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _RoomManagementService_RegisterUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _RoomManagementService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _RoomManagementService_GetUsers_Handler,
		},
		{
			MethodName: "GetUserAccessToken",
			Handler:    _RoomManagementService_GetUserAccessToken_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _RoomManagementService_UpdateUserProfile_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _RoomManagementService_RemoveUser_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _RoomManagementService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _RoomManagementService_GetRoom_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _RoomManagementService_GetRooms_Handler,
		},
		{
			MethodName: "UpdateRoomProfile",
			Handler:    _RoomManagementService_UpdateRoomProfile_Handler,
		},
		{
			MethodName: "AddUserToRoom",
			Handler:    _RoomManagementService_AddUserToRoom_Handler,
		},
		{
			MethodName: "KickUserFromRoom",
			Handler:    _RoomManagementService_KickUserFromRoom_Handler,
		},
		{
			MethodName: "DestroyRoom",
			Handler:    _RoomManagementService_DestroyRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signalling.proto",
}

// SignallingServiceClient is the client API for SignallingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignallingServiceClient interface {
	GetProfile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Profile, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileParam, opts ...grpc.CallOption) (*Profile, error)
	GetMyRooms(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Rooms, error)
	GetRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Room, error)
	OfferSessionDescription(ctx context.Context, in *SDPParam, opts ...grpc.CallOption) (*empty.Empty, error)
	AnswerSessionDescription(ctx context.Context, in *SDPParam, opts ...grpc.CallOption) (*empty.Empty, error)
	SubscribeSDPEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (SignallingService_SubscribeSDPEventClient, error)
	SubscribeUserJoinLeaveRoomEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (SignallingService_SubscribeUserJoinLeaveRoomEventClient, error)
}

type signallingServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignallingServiceClient(cc *grpc.ClientConn) SignallingServiceClient {
	return &signallingServiceClient{cc}
}

func (c *signallingServiceClient) GetProfile(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileParam, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) GetMyRooms(ctx context.Context, in *PaginationParam, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/GetMyRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) GetRoom(ctx context.Context, in *GetRoomParam, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) OfferSessionDescription(ctx context.Context, in *SDPParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/OfferSessionDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) AnswerSessionDescription(ctx context.Context, in *SDPParam, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.SignallingService/AnswerSessionDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signallingServiceClient) SubscribeSDPEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (SignallingService_SubscribeSDPEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SignallingService_serviceDesc.Streams[0], "/protos.SignallingService/SubscribeSDPEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &signallingServiceSubscribeSDPEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SignallingService_SubscribeSDPEventClient interface {
	Recv() (*SDP, error)
	grpc.ClientStream
}

type signallingServiceSubscribeSDPEventClient struct {
	grpc.ClientStream
}

func (x *signallingServiceSubscribeSDPEventClient) Recv() (*SDP, error) {
	m := new(SDP)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *signallingServiceClient) SubscribeUserJoinLeaveRoomEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (SignallingService_SubscribeUserJoinLeaveRoomEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SignallingService_serviceDesc.Streams[1], "/protos.SignallingService/SubscribeUserJoinLeaveRoomEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &signallingServiceSubscribeUserJoinLeaveRoomEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SignallingService_SubscribeUserJoinLeaveRoomEventClient interface {
	Recv() (*UserJoinLeaveRoomEvent, error)
	grpc.ClientStream
}

type signallingServiceSubscribeUserJoinLeaveRoomEventClient struct {
	grpc.ClientStream
}

func (x *signallingServiceSubscribeUserJoinLeaveRoomEventClient) Recv() (*UserJoinLeaveRoomEvent, error) {
	m := new(UserJoinLeaveRoomEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SignallingServiceServer is the server API for SignallingService service.
type SignallingServiceServer interface {
	GetProfile(context.Context, *empty.Empty) (*Profile, error)
	UpdateProfile(context.Context, *UpdateProfileParam) (*Profile, error)
	GetMyRooms(context.Context, *PaginationParam) (*Rooms, error)
	GetRoom(context.Context, *GetRoomParam) (*Room, error)
	OfferSessionDescription(context.Context, *SDPParam) (*empty.Empty, error)
	AnswerSessionDescription(context.Context, *SDPParam) (*empty.Empty, error)
	SubscribeSDPEvent(*empty.Empty, SignallingService_SubscribeSDPEventServer) error
	SubscribeUserJoinLeaveRoomEvent(*empty.Empty, SignallingService_SubscribeUserJoinLeaveRoomEventServer) error
}

// UnimplementedSignallingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignallingServiceServer struct {
}

func (*UnimplementedSignallingServiceServer) GetProfile(ctx context.Context, req *empty.Empty) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedSignallingServiceServer) UpdateProfile(ctx context.Context, req *UpdateProfileParam) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedSignallingServiceServer) GetMyRooms(ctx context.Context, req *PaginationParam) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyRooms not implemented")
}
func (*UnimplementedSignallingServiceServer) GetRoom(ctx context.Context, req *GetRoomParam) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (*UnimplementedSignallingServiceServer) OfferSessionDescription(ctx context.Context, req *SDPParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferSessionDescription not implemented")
}
func (*UnimplementedSignallingServiceServer) AnswerSessionDescription(ctx context.Context, req *SDPParam) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerSessionDescription not implemented")
}
func (*UnimplementedSignallingServiceServer) SubscribeSDPEvent(req *empty.Empty, srv SignallingService_SubscribeSDPEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSDPEvent not implemented")
}
func (*UnimplementedSignallingServiceServer) SubscribeUserJoinLeaveRoomEvent(req *empty.Empty, srv SignallingService_SubscribeUserJoinLeaveRoomEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeUserJoinLeaveRoomEvent not implemented")
}

func RegisterSignallingServiceServer(s *grpc.Server, srv SignallingServiceServer) {
	s.RegisterService(&_SignallingService_serviceDesc, srv)
}

func _SignallingService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).GetProfile(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).UpdateProfile(ctx, req.(*UpdateProfileParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_GetMyRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).GetMyRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/GetMyRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).GetMyRooms(ctx, req.(*PaginationParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).GetRoom(ctx, req.(*GetRoomParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_OfferSessionDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SDPParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).OfferSessionDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/OfferSessionDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).OfferSessionDescription(ctx, req.(*SDPParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_AnswerSessionDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SDPParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).AnswerSessionDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SignallingService/AnswerSessionDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).AnswerSessionDescription(ctx, req.(*SDPParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignallingService_SubscribeSDPEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignallingServiceServer).SubscribeSDPEvent(m, &signallingServiceSubscribeSDPEventServer{stream})
}

type SignallingService_SubscribeSDPEventServer interface {
	Send(*SDP) error
	grpc.ServerStream
}

type signallingServiceSubscribeSDPEventServer struct {
	grpc.ServerStream
}

func (x *signallingServiceSubscribeSDPEventServer) Send(m *SDP) error {
	return x.ServerStream.SendMsg(m)
}

func _SignallingService_SubscribeUserJoinLeaveRoomEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignallingServiceServer).SubscribeUserJoinLeaveRoomEvent(m, &signallingServiceSubscribeUserJoinLeaveRoomEventServer{stream})
}

type SignallingService_SubscribeUserJoinLeaveRoomEventServer interface {
	Send(*UserJoinLeaveRoomEvent) error
	grpc.ServerStream
}

type signallingServiceSubscribeUserJoinLeaveRoomEventServer struct {
	grpc.ServerStream
}

func (x *signallingServiceSubscribeUserJoinLeaveRoomEventServer) Send(m *UserJoinLeaveRoomEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _SignallingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SignallingService",
	HandlerType: (*SignallingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _SignallingService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _SignallingService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetMyRooms",
			Handler:    _SignallingService_GetMyRooms_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _SignallingService_GetRoom_Handler,
		},
		{
			MethodName: "OfferSessionDescription",
			Handler:    _SignallingService_OfferSessionDescription_Handler,
		},
		{
			MethodName: "AnswerSessionDescription",
			Handler:    _SignallingService_AnswerSessionDescription_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeSDPEvent",
			Handler:       _SignallingService_SubscribeSDPEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeUserJoinLeaveRoomEvent",
			Handler:       _SignallingService_SubscribeUserJoinLeaveRoomEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "signalling.proto",
}
