name: deploy

on:
  push:
    branches: [master]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - uses: actions/checkout@v2
    - run: make init
    - run: make test
    - run: sed -i "s/--build-sha--/$GITHUB_SHA/g" cmd/version.go
    - run: make build-cross-linux 
    - uses: actions/upload-artifact@v1
      with:
        name: binary
        path: signalling
  
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: binary
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: asa/asa
        tag_with_ref: true
        tag_with_sha: true
